export const reportSources = [
  {
    id: "gmi-nail-salon-2025",
    label: "GMI",
    title: "Nail Salon Market Size, Share & Growth Forecasts 2035",
    url: "https://www.gminsights.com/industry-analysis/nail-salon-market",
    accessed: "06/2026",
  },
  {
    id: "blvd-salon-stats-2025",
    label: "Boulevard",
    title: "20 Salon Trends & Industry Statistics (2025)",
    url: "https://www.joinblvd.com/blog/salon-trends-industry-statistics",
    accessed: "06/2026",
  },
  {
    id: "santee-city-demographics",
    label: "City of Santee",
    title: "Population & Demographics — Santee, California",
    url: "https://www.cityofsanteeca.gov/business/economic-development/population--demographics",
    accessed: "06/2026",
  },
  {
    id: "wikipedia-santee",
    label: "Wikipedia",
    title: "Santee, California",
    url: "https://en.wikipedia.org/wiki/Santee,_California",
    accessed: "06/2026",
  },
  {
    id: "ca-bbc-art12",
    label: "CA BBC",
    title: "Article 12 — Health and Safety (Board of Barbering and Cosmetology)",
    url: "https://www.barbercosmo.ca.gov/laws_regs/art12.shtml",
    accessed: "06/2026",
  },
  {
    id: "lk-company-site",
    label: "LK Nail Salon",
    title: "Website & dịch vụ — lknailsalonsantee.com",
    url: "https://lknailsalonsantee.com",
    accessed: "06/2026",
  },
  {
    id: "lk-services-pricing",
    label: "LK Nail Salon",
    title: "Bảng giá dịch vụ — Services",
    url: "https://lknailsalonsantee.com/services",
    accessed: "06/2026",
  },
  {
    id: "brightlocal-reviews-2024",
    label: "BrightLocal",
    title: "Local Consumer Review Survey 2024",
    url: "https://www.brightlocal.com/research/local-consumer-review-survey-2024/",
    accessed: "06/2026",
  },
  {
    id: "salon-today-retention",
    label: "Salon Today",
    title: "Boulevard Report — First-time visitor retention & online booking",
    url: "https://www.salontoday.com/1088748/boulevard-report-reveals-top-performing-salons-retain-56-more-first-time-visitor",
    accessed: "06/2026",
  },
  {
    id: "cpi-east-county-income",
    label: "CPI San Diego",
    title: "Poverty, Income and Earnings in East County, 2018",
    url: "https://cpisandiego.org/poverty-income-earnings-east-county-2018/",
    accessed: "06/2026",
  },
  {
    id: "google-lk-santee",
    label: "Google",
    title: "LK Nail Salon — Google Maps / Business Profile",
    url: "https://www.google.com/maps/place/LK+Nail+Salon",
    accessed: "06/2026",
    note: "5,0★ · 276 đánh giá — embed trên lknailsalonsantee.com/services",
  },
  {
    id: "yelp-lk-santee",
    label: "Yelp",
    title: "LK Nail Salon — Santee, CA (80 reviews)",
    url: "https://www.yelp.com/biz/lk-nail-salon-santee",
    accessed: "06/2026",
    note: "Crawl Firecrawl 06/2026 — 4,5★ overall",
  },
  {
    id: "yelp-sunny-santee",
    label: "Yelp",
    title: "Sunny Nails & Spa — Santee (523 reviews)",
    url: "https://www.yelp.com/biz/sunny-nails-and-spa-santee-2",
    accessed: "06/2026",
  },
  {
    id: "yelp-polish-santee",
    label: "Yelp",
    title: "Polish Nails Spa — Santee (660 reviews)",
    url: "https://www.yelp.com/biz/polish-nails-spa-santee-3",
    accessed: "06/2026",
  },
  {
    id: "sunny-nails-santee",
    label: "Sunny Nails & Spa",
    title: "Nail Salon in Santee, CA 92071",
    url: "https://sunnynailsspasantee.com/",
    accessed: "06/2026",
  },
  {
    id: "polish-nails-santee",
    label: "Polish Nails Spa",
    title: "Polish Nails Spa LLC — Santee",
    url: "https://www.polishnailsspallcsantee.com/",
    accessed: "06/2026",
  },
  {
    id: "lavie-nails-santee",
    label: "La Vie Nails",
    title: "La Vie Nails & Spa — Santee",
    url: "https://www.yelp.com/biz/la-vie-nails-and-spa-santee",
    accessed: "06/2026",
  },
  {
    id: "bls-cosmetologists",
    label: "BLS",
    title: "Barbers, Hairstylists, and Cosmetologists — Occupational Outlook",
    url: "https://www.bls.gov/ooh/personal-care-and-service/barbers-hairstylists-and-cosmetologists.htm",
    accessed: "06/2026",
  },
];

export const marketSizing = {
  asOf: "06/2026",
  globalMarket2025: {
    value: "USD 38,8 tỷ",
    sourceId: "gmi-nail-salon-2025",
    note: "Toàn cầu, năm cơ sở 2025",
  },
  usMarket2025: {
    value: "USD 6,1 tỷ",
    sourceId: "gmi-nail-salon-2025",
    note: "Thị trường Mỹ chiếm ~77,9% Bắc Mỹ",
  },
  usGrowthCAGR: {
    value: "8% (2026–2035)",
    sourceId: "gmi-nail-salon-2025",
    note: "CAGR dự báo toàn cầu; Mỹ là thị trường trưởng thành",
  },
  hairNailCombinedUS: {
    value: "USD 90,9 tỷ (2025)",
    sourceId: "blvd-salon-stats-2025",
    note: "Tóc + nail kết hợp (IBISWorld qua Boulevard)",
  },
  salonBusinessesUS: {
    value: "~1,4 triệu",
    sourceId: "blvd-salon-stats-2025",
    note: "Salon tóc & nail tại Mỹ (2024)",
  },
  independentShare: {
    value: "62%",
    sourceId: "gmi-nail-salon-2025",
    note: "Salon độc lập — mô hình của LK",
  },
  santeePopulation: {
    value: "60.037",
    sourceId: "santee-city-demographics",
    note: "Dân số thành phố Santee (Điều tra 2020)",
  },
  eastCountyMedianIncome: {
    value: "USD 79.586",
    sourceId: "cpi-east-county-income",
    note: "Thu nhập hộ gia đình trung vị East County (2018)",
  },
  localTAMEstimate: {
    value: "USD 4,5–6,5 triệu/năm",
    sourceId: "gmi-nail-salon-2025",
    note: "Ước tính bottom-up: dân số Santee × tần suất × AOV trung bình $35–55",
  },
};

export const marketSizingLabels = {
  title: "Quy mô thị trường",
  intro:
    "Bối cảnh toàn cầu, quốc gia và ước tính thị trường địa phương quanh Woodside Ave, Santee — nơi LK Nail Salon phục vụ khách walk-in và đặt lịch.",
  rows: [
    ["Thị trường nail salon toàn cầu (2025)", "globalMarket2025"],
    ["Thị trường Mỹ (2025)", "usMarket2025"],
    ["Tốc độ tăng trưởng dự báo", "usGrowthCAGR"],
    ["Thị trường tóc + nail Mỹ (2025)", "hairNailCombinedUS"],
    ["Số salon tóc & nail tại Mỹ", "salonBusinessesUS"],
    ["Thị phần salon độc lập", "independentShare"],
    ["Dân số Santee", "santeePopulation"],
    ["Thu nhập trung vị East County", "eastCountyMedianIncome"],
    ["TAM ước tính địa phương (Santee)", "localTAMEstimate"],
  ],
};
